Repository oddstr13/jellyfin-plugin-repository-manager, pull requests merged in 2023-09, with the labels that each got.

#99 Add max-cpu-count=1 to work around file locking race condition on build
  action.yaml
  jprm/__init__.py
Labels: bugfix, feature

#100 Bump version to 0.6.0
  jprm/__init__.py
Labels: no-changelog

#101 Change publish authentication to OIDC Trusted Publisher
  .github/workflows/publish.yaml
Labels: ci

#102 Remove support for Python < 3.8.1
  .github/workflows/test.yaml
  setup.py
Labels: ci, build, breaking

#103 Automatic release prepp and publish
  .github/release-next.env
  .github/workflows/release-next-checkbox-update.yaml
  .github/workflows/release-next-create-pr.yaml
  .github/workflows/release-next-publish.yaml
Labels: ci

#106 dotenv-action needs the dotenv file
  .github/workflows/release-next-checkbox-update.yaml
  .github/workflows/release-next-create-pr.yaml
Labels: ci, no-changelog

#107 Pr-release-next-workflows-3
  .github/workflows/release-next-checkbox-update.yaml
  .github/workflows/release-next-create-pr.yaml
Labels: ci, no-changelog

#108 Release-drafter does not look for .yaml, only .yml
  .github/workflows/release-drafter.yaml
  .github/workflows/release-next-create-pr.yaml
  .github/workflows/release-next-publish.yaml
Labels: ci, no-changelog

#109 Best open the quotes you close
  .github/workflows/release-next-create-pr.yaml
Labels: ci, no-changelog

#110 Checkout needs to happen in each job
  .github/workflows/release-next-create-pr.yaml
Labels: ci, no-changelog

#111 Permissions? Who needs those?
  .github/workflows/release-next-create-pr.yaml
Labels: ci, no-changelog

#113 Pretty named workflows
  .github/workflows/release-next-checkbox-update.yaml
  .github/workflows/release-next-create-pr.yaml
  .github/workflows/release-next-publish.yaml
Labels: ci, no-changelog

#114 Less noise
  .github/workflows/release-next-create-pr.yaml
Labels: ci, no-changelog

#115 More missing quotes
  .github/workflows/release-next-checkbox-update.yaml
Labels: ci, no-changelog

#116 Checkout needs to happen everywhere
  .github/workflows/release-next-checkbox-update.yaml
Labels: ci, no-changelog

#117 Internet has lied to me
  .github/workflows/release-next-publish.yaml
Labels: ci, no-changelog

#119 Revert "Prepare for release v1.0.0"
  jprm/__init__.py
Labels: no-changelog

#118 Also branch deletion needs git checked out
  .github/workflows/release-next-publish.yaml
Labels: ci

#121 Revert "Prepare for release v1.0.0"
  jprm/__init__.py
Labels: no-changelog

#124 Specify files for twine to check
  .github/workflows/publish.yaml
Labels: ci

#127 Events by workflows don't trigger other workflows
  .github/workflows/publish.yaml
  .github/workflows/release-next-publish.yaml
Labels: ci

#128 :construction:
  .github/workflows/release-next-publish.yaml
Labels: ci

#134 🔧 Debug publish
  .github/workflows/release-next-publish.yaml
Labels: ci

#136 🔧 Debug publish 🔨
  .github/workflows/release-next-publish.yaml
Labels: ci

#137 🖹 👀 RTFM
  .github/workflows/release-next-checkbox-update.yaml
  .github/workflows/release-next-publish.yaml
Labels: ci

#138 Explicitly specify release-drafter branch
  .github/release-drafter.yaml
Labels: ci

#139 🪛 Make sure release pr is created from master
  .github/workflows/release-next-create-pr.yaml
Labels: ci

#141 🔩 Fix upload_url input to GitHub upload?
  .github/workflows/publish.yaml
Labels: ci

#143 🔍 Add debug prints for upload_url
  .github/workflows/publish.yaml
Labels: ci

#145 🔭 No github.event?
  .github/workflows/publish.yaml
Labels: ci

#147 📡 Release artifact works now, right? RIGHT?!
  .github/workflows/publish.yaml
Labels: ci
